import gc
import os
import sys
from pathlib import Path
from mpi4py import MPI
import numpy as np
import matplotlib.pyplot as plt

import dolfinx
import ufl
import basix

import beat
from beat.irksome_model import IrksomeMonodomainModel
import irksome

# We import the new solver here (assuming it was saved in the same directory or beat module)
from beat.irksome_odesolver import IrksomeODESolver

import gotranx
import gotranx.cli.gotran2ufl
from gotranx.codegen.python import Format

# 1. Define the Mitchell-Schaeffer model using the gotranx declarative language
ms_ode_code = """
parameters(
    tau_in = 0.3,
    tau_out = 6.0,
    tau_open = 120.0,
    tau_close = 150.0,
    v_gate = 0.13
)
states(
    v = 0.0,
    h = 1.0
)

h_inf = Conditional(Lt(v, v_gate), 1.0, 0.0)
tau_h = Conditional(Lt(v, v_gate), tau_open, tau_close)

dv_dt = h * (v**2 * (1.0 - v)) / tau_in - v / tau_out
dh_dt = (h_inf - h) / tau_h
"""


def generate_and_import_cell_model():
    """Generates the UFL Python module from the gotranx string and imports it."""
    # Write out the .ode file using Path
    ode_filename = Path("mitchell_schaeffer.ode")
    ode_filename.write_text(ms_ode_code)

    # Use gotranx CLI function to generate and write the python module
    gotranx.cli.gotran2ufl.main(
        fname=ode_filename,
        outname="ms_cell_model",
        format=Format.none,  # Disable formatting for speed (or use Format.black)
    )

    # Add local directory to path to import the generated file
    sys.path.insert(0, os.getcwd())
    import ms_cell_model

    return ms_cell_model


def eval_conductivity(x):
    """Evaluate conductivity based on y-coordinate bands."""
    y = x[1]
    conditions = [
        y >= 0.75,
        (y >= 0.50) & (y < 0.75),
        (y >= 0.25) & (y < 0.50),
        y < 0.25,
    ]
    choices = [2.0, 0.5, 0.125, 0.03125]
    return np.select(conditions, choices)


def eval_initial_voltage(x):
    """Stimulate the left edge of the domain."""
    return np.where(x[0] <= 0.05, 1.0, 0.0)


def run_gotranx_irksome_demo():
    comm = MPI.COMM_WORLD

    # Generate the cell model via gotranx
    if comm.rank == 0:
        print("Generating UFL Cell Model from gotranx...")
    ms_ufl = generate_and_import_cell_model()

    N = 100
    mesh = dolfinx.mesh.create_unit_square(
        comm, N, N, dolfinx.cpp.mesh.CellType.triangle,
    )
    time = dolfinx.fem.Constant(mesh, dolfinx.default_scalar_type(0.0))

    # Setup the Heterogeneous Conductivity Tensor (M)
    el_M = basix.ufl.element(family="DG", cell=mesh.basix_cell(), degree=0)
    V_M = dolfinx.fem.functionspace(mesh, el_M)
    M = dolfinx.fem.Function(V_M, name="Conductivity")
    M.interpolate(eval_conductivity)

    # Setup ODE function space
    V_ode = dolfinx.fem.functionspace(mesh, ("CG", 1))
    v_ode = dolfinx.fem.Function(V_ode, name="V_ode")

    # Setup Activation Time Function
    # Initialize with -1.0 to denote "not yet activated"
    tact_func = dolfinx.fem.Function(V_ode, name="ActivationTime")
    tact_func.x.array[:] = -1.0
    activation_threshold = 0.02

    # Get the default initialized values and indices generated by gotranx
    default_states = ms_ufl.init_state_values()
    default_params = ms_ufl.init_parameter_values()
    v_idx = ms_ufl.state_index("v")

    # Create the full state array for the ODE solver
    num_states = len(default_states)
    init_states = np.zeros((num_states, v_ode.x.array.size))

    # Fill with default resting states
    for i in range(num_states):
        init_states[i, :] = default_states[i]

    # Apply initial voltage stimulus
    v_ode.interpolate(eval_initial_voltage)
    init_states[v_idx, :] = v_ode.x.array

    # 1. Initialize the IrksomeODESolver using the generated gotranx RHS
    ode_tableau = irksome.BackwardEuler()

    def ufl_rhs_wrapper(states, t, p):
        return ms_ufl.rhs(t, states, p)

    ode = IrksomeODESolver(
        v_ode=v_ode,
        v_pde=None,  # Will map dynamically in splitting solver
        fun=ufl_rhs_wrapper,
        init_states=init_states,
        butcher_tableau=ode_tableau,
        time=time,
        num_states=num_states,
        v_index=v_idx,
        parameters=default_params,
    )

    # 2. Setup Irksome PDE Model
    pde_tableau = irksome.BackwardEuler()
    params = dict(
        petsc_options={"ksp_type": "cg", "pc_type": "bjacobi", "ksp_rtol": 1e-6},
    )

    pde = IrksomeMonodomainModel(
        time=time, mesh=mesh, M=M, butcher_tableau=pde_tableau, I_s=None, params=params,
    )

    # Bind the PDE to the ODE
    ode.v_pde = pde.state
    solver = beat.MonodomainSplittingSolver(pde=pde, ode=ode, theta=1.0)

    # Output file setup
    xdmf = dolfinx.io.XDMFFile(comm, "results_gotranx_irksome.xdmf", "w")
    xdmf.write_mesh(mesh)
    xdmf.write_function(M, 0.0)

    # Time-stepping loop
    t = 0.0
    dt = 0.1
    T_end = 2.0

    if comm.rank == 0:
        print("Starting fully implicit gotranx+Irksome simulation...")

    while t < T_end - 1e-8:
        if comm.rank == 0:
            print(f"Solving for t = {t:.2f} ms")

        solver.solve((t, t + dt), dt=dt)
        t += dt

        # --- Update Activation Times ---
        v_arr = pde.state.x.array
        tact_arr = tact_func.x.array

        # Check where voltage crossed the threshold, but tact is still -1.0
        crossed_threshold_mask = (v_arr >= activation_threshold) & (tact_arr < 0.0)
        tact_arr[crossed_threshold_mask] = t

        pde.state.name = "Voltage"
        xdmf.write_function(pde.state, t)

    xdmf.close()

    # --- Plot the Activation Map ---
    # Save to XDMF for ParaView
    with dolfinx.io.XDMFFile(comm, "activation_time.xdmf", "w") as xdmf_tact:
        xdmf_tact.write_mesh(mesh)
        xdmf_tact.write_function(tact_func, 0.0)

    # Plot 2D map with matplotlib on the root process
    if comm.rank == 0:
        print("Plotting Activation Times...")
        coords = V_ode.tabulate_dof_coordinates()

        # Mask out any nodes that never activated (if the wave didn't reach them)
        activated_mask = tact_func.x.array >= 0.0

        x = coords[activated_mask, 0]
        y = coords[activated_mask, 1]
        t_acts = tact_func.x.array[activated_mask]

        plt.figure(figsize=(8, 6))

        # A scatter plot works perfectly for unstructured DOF coordinates in 2D
        sc = plt.scatter(x, y, c=t_acts, cmap="magma", s=20)

        # Add some plot decorations
        cbar = plt.colorbar(sc)
        cbar.set_label("Activation Time (ms)", fontsize=12)
        plt.title("Activation Time Map (t_act)", fontsize=14)
        plt.xlabel("x [cm]")
        plt.ylabel("y [cm]")
        plt.grid(True, linestyle="--", alpha=0.5)
        plt.tight_layout()

        plt.savefig("activation_time_map.png", dpi=300)
        print("Saved 2D activation map to 'activation_time_map.png'.")

    # Prevent MPI hangs during cleanup
    comm.Barrier()
    del solver
    del pde
    del ode
    comm.Barrier()
    gc.collect()
    comm.Barrier()


if __name__ == "__main__":
    run_gotranx_irksome_demo()
